NOM-18/dynamic-search-widget
davejg10/nomad_app pull request #2
Opened 2024-12-11 16:15 UTC by davejg10

- Created a Widget that creates a scrollable ListView of countries and filters based on user input into the searchfield. Initially was going to make the Widget flexible enough work with cities and countries but I expect the city search result view to look/act substantially different. Can refactor later if im wrong
- Navigation to come later when we have the other screens
![image](https://github.com/user-attachments/assets/5d3fea92-645f-48ba-af23-b627b48a58de)

2024-12-12 19:05 UTC, theo-jfsm requested changes

2024-12-12 19:05 UTC, theo-jfsm commented on lib/widgets/country_searchbar.dart
> +                  //TODO navigator.pushNamed..
Add ticket number to this (if its not already covered in another one of the open PRs)

2024-12-12 19:05 UTC, theo-jfsm commented on lib/widgets/country_searchbar.dart
> +        //TODO navigator.pushNamed..
See above

2024-12-12 20:04 UTC, theo-jfsm commented on lib/widgets/country_searchbar.dart
> +                  //TODO navigator.pushNamed..
Just seen this is done in the other PR but in future we should capture todos in tickets and link them in the code

2024-12-13 15:28 UTC, davejg10 commented on lib/widgets/country_searchbar.dart
> +                  //TODO navigator.pushNamed..
Good idea

2024-12-13 15:29 UTC, davejg10 commented on lib/widgets/country_searchbar.dart
> +          filteredCountryList = widget.allCountries.where((country) => country.getName.contains(userInput)).toList();
Good point will address this

2024-12-13 15:40 UTC, davejg10 commented on .gitignore
> +/analysis_options.yaml
Yeah had a little research I think it uses the gitignore in main? Adding the file to gitignore in this branch doesnt remove the file from tracked changes in this branch weirdly

2024-12-13 15:44 UTC, davejg10 commented on .gitignore
> +/analysis_options.yaml
Tried that too but then that deletes the file in the PR

2024-12-13 15:44 UTC, davejg10 commented on .gitignore
> +/analysis_options.yaml
I _think because its in main and therefore telling git to stop tracking it means it thinks it needs to remove it from main

2024-12-13 15:45 UTC, davejg10 commented on lib/main.dart
>  class MyHomePage extends StatefulWidget {
Resolved in next PR

2024-12-13 15:47 UTC, theo-jfsm commented on .gitignore
> +/analysis_options.yaml
Does `git rm` not add a file deleted change to the PR

2024-12-13 15:47 UTC, davejg10 commented on .gitignore
> +/analysis_options.yaml
Oh I see what you mean yeah.. Okay will remove

2024-12-13 15:51 UTC, davejg10 commented on .gitignore
> +/analysis_options.yaml
git rm --cached <file-name> deletes it from git but keesps it locally

2024-12-13 16:02 UTC, theo-jfsm approved these changes

2024-12-13 16:05 UTC, merged